# http://docs.travis-ci.com/user/languages/python/

language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - nightly
    - pypy3

env:
    - DJANGO_VERSION=1.8

install:
    pip install django-bootstrap3 django-filer Django==$DJANGO_VERSION

script:
    python setup.py test
