# http://docs.travis-ci.com/user/languages/python/

language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - nightly
    - pypy3

install:
    pip install --user django-bootstrap3 django-filer

script:
    python setup.py test
